/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoestoque;

import com.mysql.jdbc.Statement;
import java.awt.List;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author 47127512022.2
 */
public class TelaCadastroEstoque extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroEstoque
     */
    public TelaCadastroEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        emp_tabela = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        fornecedor = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        quantidade = new javax.swing.JTextField();
        preco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dadosConsulta = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        deletar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        tipo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        filtragem = new javax.swing.JTextField();
        filtrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(891, 567));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        emp_tabela.setBorder(new javax.swing.border.MatteBorder(null));
        emp_tabela.setForeground(new java.awt.Color(0, 51, 255));
        emp_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        emp_tabela.setSelectionBackground(new java.awt.Color(51, 51, 51));
        emp_tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emp_tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(emp_tabela);

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("DATA");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("TIPO");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("FORNECEDOR");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("QUANTIDADE");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("PREÇO");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("NOME");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("PESQUISA");

        dadosConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadosConsultaActionPerformed(evt);
            }
        });

        cadastrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cadastrar.setText("INCLUIR");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        deletar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        deletar.setText("EXCLUIR");
        deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletarActionPerformed(evt);
            }
        });

        limpar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        limpar.setText("LIMPAR");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        voltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        voltar.setText("VOLTAR");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hambúrguer", "Pão Brioche", "Queijo Cheedar", "Bacon", "Presunto", "Queijo Mussarela", "Ovos", "Katchup", "Maionese", "Mostarda", "Bebidas", " " }));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("FILTRO");

        filtragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtragemActionPerformed(evt);
            }
        });

        filtrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        filtrar.setText("FILTRAR");
        filtrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filtrarMouseClicked(evt);
            }
        });
        filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dadosConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(130, 130, 130)
                                    .addComponent(deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(128, 128, 128)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(filtragem, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(248, 248, 248)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dadosConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
       
        String url = "jdbc:mysql://localhost/estoque";
        String sql = "INSERT INTO produtos(data,nome,fornecedor,tipo,quantidade,preco) values ('"+data.getText()+"','"+nome.getText()+"','"+fornecedor.getText()+"','"+tipo.getSelectedItem()+"','"+quantidade.getText()+"','"+(Double.parseDouble(preco.getText()))+"')";


        
        
       try{
        Connection conexao = DriverManager.getConnection(url, "root","");
        
        PreparedStatement incluir = conexao.prepareStatement(sql);
        
        incluir.executeUpdate();
        
         formWindowOpened(null);
        
        JOptionPane.showMessageDialog(null,"Dados incluídos com sucesso!");
        
         data.setText("");
         nome.setText("");
         fornecedor.setText("");                                        
         tipo.setSelectedItem("");
         quantidade.setText("");
         preco.setText("");
        }
        
        catch(Exception erro){
            
            JOptionPane.showMessageDialog(null,"Erro na Conexão com o banco de dados");
            
        
        }
         
        
        
    }//GEN-LAST:event_cadastrarActionPerformed

    private void deletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarActionPerformed
        
		   int id = Integer.parseInt( emp_tabela.getValueAt(emp_tabela.getSelectedRow(),0).toString() );

	   	   String url = "jdbc:mysql://localhost/estoque"; 
	   	   String sql = "DELETE FROM produtos WHERE id = ? ";

	  	   try 
	  	   {

	     	    Connection conexao = DriverManager.getConnection(url, "root","");

	     	    PreparedStatement excluir = conexao.prepareStatement(sql); 

		    int r = JOptionPane.showConfirmDialog(this,"Tem certeza de que quer excluir item selecionado?");

		    r = id;

                    String R = String.valueOf(r); 

                    excluir.setString(1,R);

	            excluir.executeUpdate();

                    formWindowOpened(null);

	     	    JOptionPane.showMessageDialog(null,"Dados deletados com sucesso!");
		        
	   	  }
	  
	   	 catch(Exception erro) { 
           
                  JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           	}

    
        
    }//GEN-LAST:event_deletarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        
         data.setText("");
         nome.setText("");
         fornecedor.setText("");                                        
         tipo.setSelectedItem("");
         quantidade.setText("");
         preco.setText("");

 
    }//GEN-LAST:event_limparActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        
        
        dispose();
        
    }//GEN-LAST:event_voltarActionPerformed

    private void emp_tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_tabelaMouseClicked
        
         int ID = Integer.parseInt(emp_tabela.getValueAt(emp_tabela.getSelectedRow(),0).toString());

	        String url = "jdbc:mysql://localhost/estoque"; 
	        String sql = "SELECT * FROM produtos WHERE id = "+ID;

	        try 
	        {

 	            Connection conexao = DriverManager.getConnection(url, "root", "");

	            PreparedStatement pesquisar = conexao.prepareStatement(sql);

	            ResultSet res = pesquisar.executeQuery();

		    while (res.next()) {
                        
                        data.setText(res.getString("data"));
			nome.setText(res.getString("nome"));
			fornecedor.setText(res.getString("fornecedor"));
			tipo.setSelectedItem(res.getString("tipo"));
			quantidade.setText(res.getString("quantidade"));
                        preco.setText(res.getString("preco"));

		    }

		}
	   	catch(Exception erro) { 
           
                  JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           	}

        
    }//GEN-LAST:event_emp_tabelaMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
                String url = "jdbc:mysql://localhost/estoque"; 
	        String sql = "SELECT * FROM produtos";

	        try 
	        {

 	            Connection conexao = DriverManager.getConnection(url, "root", "");

	            PreparedStatement pesquisar = conexao.prepareStatement(sql);

	            ResultSet res = pesquisar.executeQuery();

		    res.last();

		    int linha  = res.getRow();
		    int coluna = res.getMetaData().getColumnCount();

		    res.beforeFirst();

		    String linhaData [][] = new String[linha][coluna];
		    int l = 0;

		    while (res.next()) {

			for (int i = 0; i < coluna; i++) {

			    linhaData[l][i] = res.getString(i+1);

			}
			l++;

  		    }
			
		    String [] colunaNome = {"id","data","nome","fornecedor","tipo","quantidade","preco",""};

		    DefaultTableModel model = (DefaultTableModel)emp_tabela.getModel(); //importar o DefaultTableModel

		    model.setDataVector(linhaData, colunaNome);
		}

	   	catch(Exception erro) { 
           
                  JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           	}

               
                dadosConsulta.setText("");

        
        
    }//GEN-LAST:event_formWindowOpened

    private void filtragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtragemActionPerformed
 
        
        
    }//GEN-LAST:event_filtragemActionPerformed

    private void filtrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarActionPerformed
/*
		int ID = Integer.parseInt(emp_tabela.getValueAt(emp_tabela.getSelectedRow(),0).toString());

	        String url = "jdbc:mysql://localhost/BD_EMPREGADOS"; 
	        String sql = "SELECT * FROM empregados WHERE nome = ";

	        try 
	        {

 	            Connection conexao = DriverManager.getConnection(url, "root", "");

	            PreparedStatement pesquisar = conexao.prepareStatement(sql);

	            ResultSet res = pesquisar.executeQuery();

		    while (res.next()) {

			nome.setText(res.getString("nome"));
			eemail.setText(res.getString("email"));
			emp_fone.setText(res.getString("telefone"));
			emp_endereço.setText(res.getString("endereço"));

		    }

		}
	   	catch(Exception erro) { 
           
                  JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           	}
*/
    }//GEN-LAST:event_filtrarActionPerformed

    private void dadosConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadosConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dadosConsultaActionPerformed

    private void filtrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filtrarMouseClicked
        
              int Data = Integer.parseInt(emp_tabela.getValueAt(emp_tabela.getSelectedRow(),0).toString());

	        String url = "jdbc:mysql://localhost/estoque"; 
	        String sql = "SELECT * FROM produtos WHERE data = "+Data;  

	        try 
	        {

 	            Connection conexao = DriverManager.getConnection(url, "root", "");

	            PreparedStatement pesquisar = conexao.prepareStatement(sql);

	            ResultSet res = pesquisar.executeQuery();

		    while (res.next()) {
                        
                        data.setText(res.getString("data"));
			nome.setText(res.getString("nome"));
			fornecedor.setText(res.getString("fornecedor"));
			tipo.setSelectedItem(res.getString("tipo"));
			quantidade.setText(res.getString("quantidade"));
                        preco.setText(res.getString("preco"));

		    }

		}
	   	catch(Exception erro) { 
           
                  JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           	}

        
        
    }//GEN-LAST:event_filtrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField dadosConsulta;
    private javax.swing.JTextField data;
    private javax.swing.JButton deletar;
    private javax.swing.JTable emp_tabela;
    private javax.swing.JTextField filtragem;
    private javax.swing.JButton filtrar;
    private javax.swing.JTextField fornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField preco;
    private javax.swing.JTextField quantidade;
    private javax.swing.JComboBox<String> tipo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
