/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoestoque;

import java.sql.Connection;
import modelo.ModeloExibeEstoque;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */
public class TelaVerificarEstoque extends javax.swing.JFrame {

    /**
     * Creates new form TelaVerificarEstoque
     */
    public TelaVerificarEstoque() {
        initComponents();
    }
    
    
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        quantidade = new javax.swing.JTextField();
        preco_custo = new javax.swing.JTextField();
        fornecedor = new javax.swing.JTextField();
        preco_venda = new javax.swing.JTextField();
        tipo = new javax.swing.JTextField();
        Incluir = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        dadoConsulta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        emp_tabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        data = new javax.swing.JTextField();
        nome1 = new javax.swing.JTextField();
        fornecedor1 = new javax.swing.JTextField();
        preco = new javax.swing.JTextField();
        tipo1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        quantidade1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        data1 = new javax.swing.JTextField();
        pesquisa = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        cadastrar = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        Alterar = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Data:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(44, 7, 50, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Quantidade:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(7, 47, 82, 20);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Fornecedor:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(258, 47, 81, 20);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nome:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(255, 7, 45, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Fornecedor:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(495, 7, 81, 20);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tipo:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(546, 47, 34, 20);
        jPanel1.add(nome);
        nome.setBounds(107, 7, 114, 22);
        jPanel1.add(quantidade);
        quantidade.setBounds(107, 47, 114, 22);
        jPanel1.add(preco_custo);
        preco_custo.setBounds(345, 7, 132, 22);
        jPanel1.add(fornecedor);
        fornecedor.setBounds(345, 47, 132, 22);
        jPanel1.add(preco_venda);
        preco_venda.setBounds(586, 7, 149, 22);
        jPanel1.add(tipo);
        tipo.setBounds(586, 47, 149, 22);

        Incluir.setText("INCLUIR");
        Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncluirActionPerformed(evt);
            }
        });
        jPanel1.add(Incluir);
        Incluir.setBounds(88, 81, 90, 22);

        Excluir.setText("EXCLUIR");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(Excluir);
        Excluir.setBounds(280, 80, 100, 22);

        Limpar.setText("LIMPAR");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });
        jPanel1.add(Limpar);
        Limpar.setBounds(490, 80, 90, 22);

        Voltar.setText("VOLTAR");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jPanel1.add(Voltar);
        Voltar.setBounds(690, 80, 90, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Dado De Operação");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(760, 0, 130, 20);
        jPanel1.add(dadoConsulta);
        dadoConsulta.setBounds(760, 30, 120, 22);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(915, 550));
        setPreferredSize(new java.awt.Dimension(915, 550));
        setResizable(false);
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        emp_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        emp_tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emp_tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(emp_tabela);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("DATA");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 25, 31, 14);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("NOME");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(240, 25, 34, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("TIPO");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 75, 27, 14);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("FORNECEDOR");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(490, 25, 78, 14);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("PREÇO");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(490, 75, 40, 14);

        jButton5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton5.setText("PESQUISAR");
        jPanel2.add(jButton5);
        jButton5.setBounds(590, 140, 97, 20);
        jPanel2.add(data);
        data.setBounds(60, 20, 150, 25);
        jPanel2.add(nome1);
        nome1.setBounds(290, 20, 170, 25);
        jPanel2.add(fornecedor1);
        fornecedor1.setBounds(590, 20, 170, 25);
        jPanel2.add(preco);
        preco.setBounds(540, 70, 130, 25);

        tipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha uma Opção", "Hambúrguer", "Pão brioche", "Queijo cheedar", "Queijo mussarela", "Queijo Prato", "Presunto", "Bacon", "Ovos", "Bebidas", " " }));
        jPanel2.add(tipo1);
        tipo1.setBounds(60, 70, 140, 25);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("QUANTIDADE");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(220, 75, 100, 20);
        jPanel2.add(quantidade1);
        quantidade1.setBounds(310, 70, 170, 25);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("PESQUISA");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(800, 10, 60, 14);
        jPanel2.add(data1);
        data1.setBounds(790, 30, 90, 22);

        pesquisa.setText("Pesquisar");
        pesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaMouseClicked(evt);
            }
        });
        pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaActionPerformed(evt);
            }
        });
        jPanel2.add(pesquisa);
        pesquisa.setBounds(790, 60, 90, 22);
        jPanel2.add(id);
        id.setBounds(800, 100, 64, 22);

        cadastrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cadastrar.setText("INCLUIR");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        limpar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        limpar.setText("LIMPAR");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        excluir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        excluir.setText("DELETAR");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        voltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        voltar.setText("VOLTAR");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Alterar)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Alterar)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
       nome.setText("");
       quantidade.setText("");
       fornecedor.setText("");
       preco_custo.setText("");
       preco_venda.setText("");
       tipo.setText("");
    }//GEN-LAST:event_LimparActionPerformed

    private void IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncluirActionPerformed
 /*   String url = "jdbc:mysql://localhost/estoque";
    String sql = "INSERT INTO produto (nome,quantidade,fornecedor,preco_custo,preco_venda,tipo) values ('"+nome.getText()+"','"+quantidade.getText()+"','"+fornecedor.getText()+"','"+preco_custo.getText()+"','"+preco_venda.getText()+"','"+tipo.getText()+"')";
    
    try{
        Connection conexao = DriverManager.getConnection(url, "root","");
        
        PreparedStatement incluir = conexao.prepareStatement(sql);
        
         incluir.executeUpdate();
         
          formWindowOpened(null);

	     	   JOptionPane.showMessageDialog(null,"Dados incluídos com sucesso!");

                   nome.setText("");
                   quantidade.setText("");
                   fornecedor.setText("");
                   preco_custo.setText("");
                   preco_venda.setText("");
                   tipo.setText("");
    
    }
    catch(Exception erro){
    
                  JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
    }

        

*/
    }//GEN-LAST:event_IncluirActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
                String url = "jdbc:mysql://localhost/estoque"; 
	        String sql = "SELECT * FROM produtos";

	        try 
	        {

 	            Connection conexao = DriverManager.getConnection(url, "root", "");

	            PreparedStatement pesquisar = conexao.prepareStatement(sql);

	            ResultSet res = pesquisar.executeQuery();

		    res.last();

		    int linha  = res.getRow();
		    int coluna = res.getMetaData().getColumnCount();

		    res.beforeFirst();

		    String linhaData [][] = new String[linha][coluna];
		    int l = 0;

		    while (res.next()) {

			for (int i = 0; i < coluna; i++) {

			    linhaData[l][i] = res.getString(i+1);

			}
			l++;

  		    }
			
		    String [] colunaNome = {"id","data","nome","fornecedor","tipo","quantidade","preço"};

		    DefaultTableModel model = (DefaultTableModel)emp_tabela.getModel(); //importar o DefaultTableModel

		    model.setDataVector(linhaData, colunaNome);
		}

	   	catch(Exception erro) { 
           
                  JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           	}

        
    }//GEN-LAST:event_formWindowOpened

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
                   String url = "jdbc:mysql://localhost/estoque"; 
	   	   String sql = "DELETE FROM produtos WHERE nome = ?";

	  	   try 
	  	   {

	     	    Connection conexao = DriverManager.getConnection(url, "root","");

	     	    PreparedStatement excluir = conexao.prepareStatement(sql); 

	            excluir.setString(1,dadoConsulta.getText());

	            excluir.executeUpdate();

                    formWindowOpened(null);

	     	    JOptionPane.showMessageDialog(null,"Dados deletados com sucesso!");
                    
                    dadoConsulta.setText("");
    
	   	  }
	  
	   	 catch(Exception erro) { 
           
                  JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           	}
    }//GEN-LAST:event_ExcluirActionPerformed

    private void emp_tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_tabelaMouseClicked
        
        int ID = Integer.parseInt(emp_tabela.getValueAt(emp_tabela.getSelectedRow(),0).toString());

	        String url = "jdbc:mysql://localhost/estoque"; 
	        String sql = "SELECT * FROM produtos WHERE id = "+ID;

	        try 
	        {

 	            Connection conexao = DriverManager.getConnection(url, "root", "");

	            PreparedStatement pesquisar = conexao.prepareStatement(sql);

	            ResultSet res = pesquisar.executeQuery();

		    while (res.next()) {

			data.setText(res.getString("data"));
                        nome1.setText(res.getString("nome"));
			fornecedor1.setText(res.getString("fornecedor"));
                        tipo1.setSelectedItem(res.getString("tipo"));
                        quantidade1.setText(res.getString("quantidade"));
			preco.setText(res.getString("preco"));
                        id.setText(res.getString("id"));

		    }

		}
	   	catch(Exception erro) { 
           
                  JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           	}
        
    }//GEN-LAST:event_emp_tabelaMouseClicked

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed

        try{
            String url = "jdbc:mysql://localhost/estoque";
            String sql = "INSERT INTO produtos(data,nome,fornecedor,tipo,quantidade,preco) values ('"+data.getText()+"','"+nome1.getText()+"','"+fornecedor1.getText()+"','"+tipo1.getSelectedItem()+"','"+quantidade1.getText()+"','"+(Double.parseDouble(preco.getText()))+"')";

            Connection conexao = DriverManager.getConnection(url, "root","");

            PreparedStatement incluir = conexao.prepareStatement(sql);

            incluir.executeUpdate();

            formWindowOpened(null);

            JOptionPane.showMessageDialog(null,"Dados incluídos com sucesso!");

            data.setText("");
            nome.setText("");
            fornecedor.setText("");
            tipo1.setSelectedItem("");
            quantidade1.setText("");
            preco.setText("");
        }

        catch(Exception erro){

            JOptionPane.showMessageDialog(null,"Erro na Conexão com o banco de dados");

        }

    }//GEN-LAST:event_cadastrarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed

        data.setText("");
        nome.setText("");
        fornecedor.setText("");
        tipo1.setSelectedItem("");
        quantidade.setText("");
        preco.setText("");

    }//GEN-LAST:event_limparActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed

        dispose();

    }//GEN-LAST:event_voltarActionPerformed

    private void pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaActionPerformed
                 
    	
	        String url = "jdbc:mysql://localhost/estoque"; 
	        String sql = "SELECT * FROM produtos WHERE nome = '"+data1.getText()+"'";

	        try 
	        {

 	            Connection conexao = DriverManager.getConnection(url, "root", "");

	            PreparedStatement pesquisar = conexao.prepareStatement(sql);

	            ResultSet res = pesquisar.executeQuery();

		    while (res.next()) {

			data.setText(res.getString("data"));
                        nome1.setText(res.getString("nome"));
			fornecedor1.setText(res.getString("fornecedor"));
                        tipo.setText(res.getString("tipo"));
                        quantidade1.setText(res.getString("quantidade"));
			preco.setText(res.getString("preco"));

		    }

		}
	   	catch(Exception erro) { 
           
                  JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           	}
        
   
    }//GEN-LAST:event_pesquisaActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
                    String url = "jdbc:mysql://localhost/estoque"; 
	   	   String sql = "DELETE FROM produtos WHERE id = ?";

	  	   try 
	  	   {
                    int id = Integer.parseInt( emp_tabela.getValueAt(emp_tabela.getSelectedRow(),0).toString() );
                       
	     	    Connection conexao = DriverManager.getConnection(url, "root","");

	     	    PreparedStatement excluir = conexao.prepareStatement(sql); 

	           int r = JOptionPane.showConfirmDialog(this, "Tem certeza de que desejar excluir o item selecionado?");
                   
                   r = id;
                   
                   String R = String.valueOf(r);
                   
                   excluir.setString(1, R);

	            excluir.executeUpdate();

                    formWindowOpened(null);

	     	    JOptionPane.showMessageDialog(null,"Dados deletados com sucesso!");
                    
                    
    
	   	  }
	  
	   	 catch(Exception erro) { 
           
                  JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           	}
    }//GEN-LAST:event_excluirActionPerformed

    private void pesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaMouseClicked
       	       //  int Data = Integer.parseInt(emp_tabela.getValueAt(emp_tabela.getSelectedRow(),1).toString());
        
                String url = "jdbc:mysql://localhost/estoque"; 
	        String sql = "SELECT * FROM produtos WHERE data = '"+data1.getText()+"'";

	        try 
	        {

 	            Connection conexao = DriverManager.getConnection(url, "root", "");

	            PreparedStatement pesquisar = conexao.prepareStatement(sql);

	            ResultSet res = pesquisar.executeQuery();

		    while (res.next()) {

                        data.setText(res.getString("data"));
                        nome1.setText(res.getString("nome"));
			fornecedor1.setText(res.getString("fornecedor"));
                        tipo1.setSelectedItem(res.getString("tipo"));
                        quantidade1.setText(res.getString("quantidade"));
			preco.setText(res.getString("preco"));
                        
                        JOptionPane.showMessageDialog(null, "=================================\n"+
                                                            "Dados da Pesquisa\n"+
                                                            "Data: "+data1.getText()+"\n"+
                                                            "Nome: "+nome1.getText()+"\n"+
                                                            "Fornecedor: "+fornecedor1.getText()+"\n"+
                                                            "Tipo: "+tipo1.getSelectedItem()+"\n"+
                                                            "Quantidade: "+quantidade1.getText()+"\n"+
                                                            "Preço: "+preco.getText()+"\n"+
                                                            "================================");

		    }

		}
	   	catch(Exception erro) { 
           
                  JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           	}
    }//GEN-LAST:event_pesquisaMouseClicked

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
                    String url = "jdbc:mysql://localhost/estoque"; 
	   	   String sql = "UPDATE produtos SET quantidade = '"+quantidade1.getText()+"' WHERE id = '"+id.getText()+"' ";

	  	   try 
	  	   {

	     	    Connection conexao = DriverManager.getConnection(url, "root","");

	     	    PreparedStatement alterar = conexao.prepareStatement(sql); 

	            alterar.executeUpdate();

                    formWindowOpened(null);

	     	    JOptionPane.showMessageDialog(null,"Quantidade alterada com Sucesso!");
                    
                    
    
	   	  }
	  
	   	 catch(Exception erro) { 
           
                  JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           	}
    }//GEN-LAST:event_AlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVerificarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVerificarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVerificarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVerificarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVerificarEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Incluir;
    private javax.swing.JButton Limpar;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton cadastrar;
    private javax.swing.JTextField dadoConsulta;
    private javax.swing.JTextField data;
    private javax.swing.JTextField data1;
    private javax.swing.JTable emp_tabela;
    private javax.swing.JButton excluir;
    private javax.swing.JTextField fornecedor;
    private javax.swing.JTextField fornecedor1;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nome1;
    private javax.swing.JButton pesquisa;
    private javax.swing.JTextField preco;
    private javax.swing.JTextField preco_custo;
    private javax.swing.JTextField preco_venda;
    private javax.swing.JTextField quantidade;
    private javax.swing.JTextField quantidade1;
    private javax.swing.JTextField tipo;
    private javax.swing.JComboBox<String> tipo1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
